site_name: Hector Steenbergen-Cockerton
site_description: Urban Sociology & Energy Transition Researcher
site_author: Hector Steenbergen-Cockerton
site_url: https://hec-steen.github.io

nav:
  - Home: index.md
  - About: about.md
  - Blog: blog/index.md
  - Art: drawings.md
  - Publications: publications.md

theme:
  name: material
  language: en
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Tinos
    code: Roboto Mono
  icon:
    logo: material/book-open-variant
  favicon: favicon.png
  features:
    - navigation.top
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - header.autohide
    - content.tooltips

plugins:
  - search
  - blog:
      blog_dir: blog
      archive: false
      categories: true
      post_url_format: "{slug}"
  - social:
      cards: true
      cards_dir: assets/images/social
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/linkedin
      name: Connect on LinkedIn
      link: https://www.linkedin.com/in/your-linkedin/
    - icon: fontawesome/regular/envelope
      name: Send me an email
      link: mailto:your@email.com

hooks:
  - hooks/socialmedia.py

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/scripts/fade-in.js

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
